window.BASS_ARTISTS = [
  { id: '4hero', name: '4hero', year: 1990, track: 'Mr. Kirk’s Nightmare', source: 'https://ra.co/reviews/33882', genres: ['Jungle', 'Breakbeat'], tags: ['hardcore roots', 'Reinforced'], bio: 'Their early breakbeat experiments helped lay the groundwork for jungle. “Mr. Kirk’s Nightmare” carried their sound from the studio into the rave.' },
  { id: 'goldie', name: 'Goldie', year: 1992, track: 'Terminator', source: 'https://www.metalheadz.co.uk/artist/goldie', genres: ['Jungle', 'Drum & bass'], tags: ['Metalheadz', 'atmospheric'], bio: '“Terminator” put Goldie’s name on the map with time-stretched breaks. He went on to found Metalheadz and make “Timeless,” a landmark drum & bass album.' },
  { id: 'andy-c', name: 'Andy C', year: 1993, track: 'Valley of the Shadows (as Origin Unknown)', source: 'https://www.ramrecords.com/info', genres: ['Jungle', 'Drum & bass'], tags: ['RAM Records', 'dancefloor'], bio: 'Andy C and Ant Miles made “Valley of the Shadows” as Origin Unknown. Its ominous sample and rolling breaks became a jungle touchstone.' },
  { id: 'roni-size', name: 'Roni Size / Reprazent', year: 1997, track: 'Brown Paper Bag', source: 'https://www.officialcharts.com/songs/roni-size-reprazent-brown-paper-bag/', genres: ['Drum & bass'], tags: ['Bristol', 'live ensemble'], bio: 'Reprazent brought Bristol drum & bass to a wider audience with live instrumentation and the unmistakable bass line of “Brown Paper Bag.”' },
  { id: 'friction', name: 'Friction', year: 2007, track: 'Back to Your Roots (Friction & K-Tee remix)', source: 'https://www.shogunaudio.co.uk/pages/jonny-l-back-to-your-roots-friction-k-tee-remix', genres: ['Drum & bass'], tags: ['Shogun Audio', 'dancefloor'], bio: 'A major DJ and the founder of Shogun Audio, Friction turned Jonny L’s “Back to Your Roots” into a widely played drum & bass anthem with K-Tee.' },
  { id: 'chase-status', name: 'Chase & Status', year: 2007, track: 'Hurt You / Sell Me Your Soul', source: 'https://www.officialcharts.com/songs/chase-status-hurt-yousell-me-your-soul/', genres: ['Drum & bass', 'Dubstep'], tags: ['RAM Records', 'crossover'], bio: 'Their first UK dance chart No. 1 announced a duo able to move between underground bass pressure and crossover hits.' },
  { id: 'camo-krooked', name: 'Camo & Krooked', year: 2010, track: 'Turn Up (The Music)', source: 'https://www.hospitalrecords.com/products/various-artists-sick-music-2', genres: ['Drum & bass'], tags: ['Hospital Records', 'dancefloor'], bio: 'The Austrian duo’s intricate, high-energy production made them one of the defining drum & bass partnerships of the 2010s.' },
  { id: 'nia-archives', name: 'Nia Archives', year: 2020, track: 'Sober Feels', source: 'https://mixmag.net/feature/nia-archives-jungle-interview-cover-feature', genres: ['Jungle', 'Drum & bass'], tags: ['jungle revival', 'vocal'], bio: 'Nia Archives brought intimate songwriting and fast chopped breaks together on “Sober Feels,” helping introduce jungle to a new generation.' }
];

window.BASS_CONNECTIONS = [
  { a: '4hero', b: 'goldie', type: 'Label', reason: 'Goldie’s early Rufige Kru records came through 4hero’s Reinforced label.', source: 'https://concord.com/publishing-roster/goldie/' },
  { a: 'andy-c', b: 'chase-status', type: 'Label', reason: 'Andy C’s RAM Records signed Chase & Status.', source: 'https://www.ramrecords.com/info' },
  { a: 'goldie', b: 'nia-archives', type: 'Support', reason: 'Goldie voiced an introduction on Nia’s “Silence Is Loud” album.', source: 'https://music.apple.com/us/album/silence-is-loud/1728850551' }
];
